#!/usr/bin/env python

from __future__ import print_function

import argparse
import os
from subprocess import call
import sys

def up(args):
    try:
        call(['docker-compose', 'run', 'churn'])
    except OSError:
        print('Please install Docker and Docker Compose.', file=sys.stderr)

def down(args):
    try:
        call(['docker-compose', 'down', '--remove-orphans', '--rmi', 'local'])
    except OSError:
        print('Please install Docker and Docker Compose.', file=sys.stderr)

parser = argparse.ArgumentParser(prog='./dev')
subparsers = parser.add_subparsers(help='Available commands')

parser_up = subparsers.add_parser('up',
                                  help='Bring up the development enviroment')
parser_up.set_defaults(func=up)

parser_down = subparsers.add_parser('down',
    help='Bring down the development environment, and clean up')
parser_down.set_defaults(func=down)

args = parser.parse_args()
args.func(args)

