#!/usr/bin/env python

"""Development commands"""

from __future__ import print_function

import argparse
from subprocess import call
import sys

# pylint: disable=unused-argument

def up(args):
    try:
        # Workaround for churn.egg-info being wiped out by the volume mount
        # http://stackoverflow.com/q/31365864
        call(['docker-compose', 'run', 'churn', 'bash', '-c',
              'pip install --editable .'])
        call(['docker-compose', 'run', 'churn'])
    except OSError:
        print('Please install Docker and Docker Compose.', file=sys.stderr)

def down(args):
    try:
        call(['docker-compose', 'down', '--remove-orphans', '--rmi', 'local'])
    except OSError:
        print('Please install Docker and Docker Compose.', file=sys.stderr)

def lint(args):
    rc = call(['docker-compose', 'run', 'churn', 'bash', '-c',
               'pylint -rn ./**/*.py *.py dev'])
    exit(rc)

def main():
    parser = argparse.ArgumentParser(prog='./dev')
    subparsers = parser.add_subparsers(help='Available commands')

    parser_up = subparsers.add_parser('up',
                                      help='Bring up a development enviroment')
    parser_up.set_defaults(func=up)

    parser_down = subparsers.add_parser('down',
                                        help=('Bring down the development '
                                              'environment, and clean up'))
    parser_down.set_defaults(func=down)

    parser_lint = subparsers.add_parser('lint',
                                        help='Lint the code')
    parser_lint.set_defaults(func=lint)

    args = parser.parse_args()
    args.func(args)

if __name__ == '__main__':
    main()
