name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Lint the code
        run: ./dev lint
      - name: Test the code
        run: ./dev test
